# Generated by Django 4.2.4 on 2023-09-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.PositiveIntegerField(verbose_name='ID вакансии')),
                ('name_company', models.CharField(max_length=127, verbose_name='Название компании')),
                ('url', models.URLField(verbose_name='Ссылка на компанию')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name_company'],
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vacancy', models.PositiveIntegerField(verbose_name='ID вакансии')),
                ('name_vacancy', models.CharField(max_length=127, verbose_name='Название вакансии')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('salary', models.PositiveIntegerField(verbose_name='Зарплата')),
                ('requirement', models.TextField(verbose_name='Требования')),
                ('responsibiliti', models.TextField(max_length=1023, verbose_name='Ответственность')),
                ('date_created', models.DateTimeField(verbose_name='Дата публикации')),
                ('name_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.company', verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['id_vacancy'],
            },
        ),
    ]
