# Generated by Django 4.2.4 on 2023-09-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vacancy', models.PositiveIntegerField(unique=True, verbose_name='ID вакансии')),
                ('name_company', models.CharField(max_length=127, verbose_name='Название компании')),
                ('name_vacancy', models.CharField(max_length=127, verbose_name='Название вакансии')),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('url', models.URLField(verbose_name='Ссылка на вакансию')),
                ('salary', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата')),
                ('requirement', models.TextField(verbose_name='Требования')),
                ('responsibiliti', models.TextField(blank=True, max_length=1023, null=True, verbose_name='Ответственность')),
                ('date_created', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['id_vacancy'],
            },
        ),
    ]
