# Generated by Django 4.2.4 on 2023-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_vacancies_options_vacancies_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='requirement',
            field=models.TextField(max_length=1024, verbose_name='Требования'),
        ),
    ]
